---
# Stand up the VM shells
- hosts: localhost
  tasks:
    - name: Prepare inventory file
      template: src=../templates/pod.j2 dest=../pod

    - name: Prepare Keytab file
      template: src=../templates/keytab.sh.j2 dest=../tasks/keytab.sh mode=0744

    - name: Setup keytab file
      become: true
      shell: "../tasks/keytab.sh"

    - name: Prepare Kerberos realm configuration
      template: src=../templates/krb5.conf.j2 dest=/etc/krb5.conf.ansible mode=0644 owner=root group=root
      become: true

   - name: Set Kerberos realm configuration
     command: "cp /etc/krb5.conf.ansible /etc/krb5.conf"
     become: true

   - name: Create the keytabs folder
     file: path=/tmp/keytabs state=directory mode=0755
